DELETE FROM book;
ALTER TABLE book AUTO_INCREMENT = 1001;

DELETE FROM category;
ALTER TABLE category AUTO_INCREMENT = 1001;

INSERT INTO `category` (`name`) VALUES ('Classics'),('Fantasy'),('Mystery'),('Romance'),('Crime'),('History'),('Horror'),('Literature');

INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Wonderful Wizard of Oz', 'L. Frank Baum', 'wizofoz.jpg', 999, 7, False, True, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Mere Christianity', 'C. S. Lewis', 'merechristanity.jpg', 1529, 10, False, True, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Canterbury Tales', 'Geoffrey Chaucer', 'canterburytales.webp', 1100, 6, False, False, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Brothers Karamazov', 'Fyodor Dostoevsky', 'the-brothers-karamazov.gif', 4800, 5, True, True, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Pride and Prejudice', 'Jane Austen', 'prideandprejudice.jpg', 799, 8, False, False, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Lord of the Rings', 'J. R. R. Tolkien', 'LOTR.webp', 2499, 6, False, True, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Gullivers Travels', 'Jonathan Swift', 'gulliverstravel.webp', 795, 5, True, False, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Art of War', 'Sun Tzu', 'artofwar.webp', 995, 6, True, False, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Republic', 'Plato', 'therepublic.webp', 1300, 6, True, False, 1001);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Fairy Tale', 'Stephen King', 'fairytale.webp', 2275, 7, False, False, 1002);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Almost There', 'Farrah Rochon', 'almostthere.webp', 1599, 7, True, True, 1002);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Gods & Monsters', 'Shelby Mahurin', 'godsandmonsters.webp', 1499, 9, True, False, 1002);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('House of Salt and Sorrows', 'Erin A. Craig', 'houseofsalt.webp', 1199, 10, True, False, 1002);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Blood & Honey', 'Shelby Mahurin', 'bloodandhoney.webp', 1149, 10, True, False, 1002);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Desperation in Death', 'J. D. Robb', 'did.webp', 1499, 6, False, True, 1003);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Bullet That Missed', 'Richard Osman', 'tbtm.webp', 2399, 5, True, True, 1003);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('What Happened to the Bennetts', 'Lisa Scottoline', 'whttb.webp', 699, 8, True, True, 1003);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Treasure State: A Cassie Dewell Novel', 'C. J. Box', 'treasurestate.webp', 1375, 6, False, True, 1003);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Stolen Hours', 'Allen Eskens', 'tsh.webp', 1349, 9, False, False, 1003);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Once Upon A Time', 'Demelza Carlton', 'ouat.webp', 1235, 8, False, False, 1004);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Curse of Shadows and Thorns', 'LJ Andrews', 'cosat.webp', 2699, 6, True, False, 1004);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Howl at the Moon', 'Deborah Wilde', 'hatm.webp', 499, 8, True, True, 1004);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Beauty and the Goblin King', 'Lidiya Foxglove', 'batgk.webp', 735, 5, True, True, 1004);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Second Star to the Left', 'Megan Van Dyke', 'ssttl.webp', 1499, 9, False, True, 1004);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Adventurers Son : A Memoir', 'Roman Dial', 'tas.jpg', 493, 5, True, True, 1005);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Mountain of the Dead', 'Keith McCloskey', 'motd.jpg', 773, 7, False, True, 1005);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The ISIS Hostage', 'Puk Damsgard', 'tis.jpg', 715, 10, False, True, 1005);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Too Scared to Tell', 'Cathy Glass', 'tstt.webp', 801, 6, True, False, 1005);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Mrs. Sherlock Holmes', 'Brad Ricca', 'sh.jpg', 446, 7, False, False, 1005);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Splendid and the Vile', 'Erik Larson', 'tsatv.jpg', 605, 6, False, True, 1006);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Every Drop of Blood', 'Edward Achorn', 'edob.webp', 2800, 9, False, True, 1006);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Silk Roads : A New History of the World', 'Peter Frankopan', 'tsr.jpg', 2200, 5, True, False, 1006);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('I Alone Can Fix It', 'Carol Leonnig,�Philip Rucker', 'iacfi.webp', 1894, 7, False, False, 1006);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('From Babylon to Timbuktu', 'Rudolph R. Windsor', 'fbtt.jpg', 1395, 8, True, False, 1006);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Later', 'Stephen King', 'later.jpg', 1495, 7, True, False, 1007);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Walking Dead: Rise of the Governor', 'Robert Kirkman', 'twd.jpg', 2499, 8, True, True, 1007);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Miles Behind Us', 'Charlie Adlard', 'mbu.jpg', 1499, 10, True, False, 1007);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('End of Watch', 'Stephen King', 'eow.jpg', 1160, 9, False, False, 1007);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Hannibal Rising', 'Thomas Harris', 'hr.webp', 899, 6, False, True, 1007);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Paradise Lost', 'John Milton', 'paradiselost.jpg', 10, 6, True, True, 1008);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Frankenstein', 'Mary Shelly', 'frankenstein.webp', 795, 10, False, True, 1008);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Beauty and the Beast', 'Jeanne-Marie Leprince de Beaumont', 'beautyandbeast.jpg', 2500, 7, True, True, 1008);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('Moby Dick', 'Herman Melville', 'moby-dick.gif', 699, 8, True, False, 1008);
INSERT INTO `book` (title, author, description, price, rating, is_public, is_featured, category_id) VALUES ('The Iliad', 'Homer', 'the-iliad.gif', 699, 8, True, True, 1008);
